2022 data update
ropenscilabs/learningtower pull request #24
Opened 2024-09-10 23:41 UTC by grc54

Update 2022 data, create the data subset, update the documentation

2024-09-15 23:26 UTC, kevinwang09 requested changes

2024-09-15 23:26 UTC, kevinwang09 commented on inst/sampling.R
@grc54, please use set.seed() to guarantee reproducibility. 
@dicook, I think we should do this for every year, not just the 2022 data. However, this means that the current subset data in the package may change, so we won't be able to guarantee 'backwards compatibility'. Thoughts?

2024-09-17 13:13 UTC, grc54 reviewed
Add seed for reproducibility of dataset

2024-09-29 02:23 UTC, kevinwang09 requested changes

2024-09-29 02:23 UTC, kevinwang09 commented on inst/sampling.R
Please do the sampling process for every year, and update the small data files too.

2024-10-02 00:38 UTC, grc54 commented on inst/sampling.R
completed and updated the data files

2024-10-03 03:48 UTC, merged